# File node0.toml

[parity]
chain = "bloxberg.json"
base_path = "bloxbergData"

[network]
port = 30303
reserved_peers = "./bootnodes.txt"

[rpc]
port = 8547
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "local"

[websockets]
disable = false
port = 8548
interface = "local"
origins = ["none"]

[account]
unlock = ["0xaA84378fA41da83a9B6523bA46E45A664FbEBFC8"]
password = ["exampleNode.pwd"]

[mining]
engine_signer = "0xaa84378fa41da83a9b6523ba46e45a664fbebfc8"
reseal_on_txs = "none"
force_sealing = true

[footprint]
tracing = "on"
